#################
# LEMP PLAYBOOK #
#################
---
- hosts: "all"
  become: true
  roles:
    - nginx
    - mysql
    - php
  tasks:
  - name: "reload NGINX"
    ansible.builtin.service:
      name: "nginx"
      state: "reloaded"